import type { Prompt } from "@/engine/types";

/*
  PAL CORO — MAZO DE FÁBRICA (curado a mano, dominicano). v1.

  Este es el contenido base que viaja con la app. Es el moat: tiene que sonar
  a junte dominicano de verdad, no a IA traducida. Reglas de voz para cualquier
  cosa que se agregue después:
    - Slang natural, no forzado (coro, jangueo, bebío, dar un chance, tíguere,
      mai/pai, arrebatao, vaina, chin, qué lo que). Si suena a comercial, fuera.
    - "suave"     = sirve pa' junte familiar/mixto. Nada sexual. Cringe-free.
    - "picante"   = más atrevío: crushes, exes, coqueteo, tragos. Con gusto.
    - "sin-filtro"= lo más fuerte: confesiones, jangueos, secretos. Bold, NO explícito.
    - Los buenos RETOS meten a otra persona del coro ([B]), no piruetas en solitario.

  Routing (tag): neutral cae a cualquiera; interactivo mete a [B] sin romance;
  picante/solo-pareja se quedan dentro de parejas u objetivo bajo anti-awkward.
*/

export const SEED_PROMPTS: Prompt[] = [
  // ===========================================================================
  // VERDAD O RETO — RETOS
  // ===========================================================================

  // --- suave ---
  {
    id: "vr-r-001",
    juego: "verdad-reto",
    texto: "[A], enseña la última foto de tu galería sin filtrar.",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-002",
    juego: "verdad-reto",
    texto: "[A], imita cómo baila tu mai en una fiesta.",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-003",
    juego: "verdad-reto",
    texto: "[A], habla en inglés mascao por un minuto completo, sin parar.",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-004",
    juego: "verdad-reto",
    texto: "[A], manda un audio cantando el coro de la canción que tienes pegada.",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-005",
    juego: "verdad-reto",
    texto: "[A], imita a un motoconchista buscando pasaje en la esquina.",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-006",
    juego: "verdad-reto",
    texto: "[A], deja que [B] revise tus últimos 5 emojis usados y los juzgue.",
    tag: "interactivo",
    intensidad: "suave",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-007",
    juego: "verdad-reto",
    texto: "[A] y [B], hagan un comercial improvisado de un colmadón.",
    tag: "interactivo",
    intensidad: "suave",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-008",
    juego: "verdad-reto",
    texto: "[A], deja que [B] te ponga un apodo por el resto del juego.",
    tag: "interactivo",
    intensidad: "suave",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-009",
    juego: "verdad-reto",
    texto: "[A], baila dembow sin música por 15 segundos como si nadie te viera.",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
    tipo: "reto",
  },

  // --- picante ---
  {
    id: "vr-r-010",
    juego: "verdad-reto",
    texto: "[A], llámalo a [B] como si fueras su mai brava.",
    tag: "interactivo",
    intensidad: "picante",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-011",
    juego: "verdad-reto",
    texto: "Dale el teléfono a [B] y déjalo postear lo que quiera en tu estado, [A].",
    tag: "interactivo",
    intensidad: "picante",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-012",
    juego: "verdad-reto",
    texto: "[A], dile a [B] un piropo que de verdad le funcione.",
    tag: "picante",
    intensidad: "picante",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-013",
    juego: "verdad-reto",
    texto: "[A], muéstrale al coro tu último chat de WhatsApp sin decir con quién es.",
    tag: "neutral",
    intensidad: "picante",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-014",
    juego: "verdad-reto",
    texto: "[A], dedícale una canción a alguien del coro sin decir a quién es.",
    tag: "neutral",
    intensidad: "picante",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-015",
    juego: "verdad-reto",
    texto: "[A], manda un \"¿tas por ahí?\" a la última persona con quien hablaste.",
    tag: "neutral",
    intensidad: "picante",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-016",
    juego: "verdad-reto",
    texto: "[A], dile a [B] qué fue lo primero que pensaste cuando lo conociste.",
    tag: "interactivo",
    intensidad: "picante",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-017",
    juego: "verdad-reto",
    texto: "[A] y [B], mírense a los ojos 30 segundos sin reírse. El que se ría, pierde.",
    tag: "solo-pareja",
    intensidad: "picante",
    fuente: "fabrica",
    tipo: "reto",
  },

  // --- sin filtro ---
  {
    id: "vr-r-018",
    juego: "verdad-reto",
    texto: "[A], enséñale al coro una foto de tu ex más reciente.",
    tag: "neutral",
    intensidad: "sin-filtro",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-019",
    juego: "verdad-reto",
    texto: "[A], di el nombre del último crush que tuviste y por qué no pasó na'.",
    tag: "neutral",
    intensidad: "sin-filtro",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-020",
    juego: "verdad-reto",
    texto: "[A], dile a [B] una cosa que harías con él si nadie más estuviera mirando.",
    tag: "solo-pareja",
    intensidad: "sin-filtro",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-021",
    juego: "verdad-reto",
    texto: "[A], revisa tu galería y enseña la foto más comprometedora que te atrevas.",
    tag: "neutral",
    intensidad: "sin-filtro",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-022",
    juego: "verdad-reto",
    texto: "[A], di cuántas personas de este coro te han gustado alguna vez. Solo el número.",
    tag: "neutral",
    intensidad: "sin-filtro",
    fuente: "fabrica",
    tipo: "reto",
  },
  {
    id: "vr-r-023",
    juego: "verdad-reto",
    texto: "[A], léele al coro tu último mensaje enviado a esta hora de la madrugada.",
    tag: "neutral",
    intensidad: "sin-filtro",
    fuente: "fabrica",
    tipo: "reto",
  },

  // ===========================================================================
  // VERDAD O RETO — VERDADES
  // ===========================================================================

  // --- suave ---
  {
    id: "vr-v-001",
    juego: "verdad-reto",
    texto: "[A], ¿cuál ha sido la vergüenza más grande que has pasado en una junta?",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
    tipo: "verdad",
  },
  {
    id: "vr-v-002",
    juego: "verdad-reto",
    texto: "[A], ¿cuál es la mentira más grande que le has dicho a tu mai pa' salir?",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
    tipo: "verdad",
  },
  {
    id: "vr-v-003",
    juego: "verdad-reto",
    texto: "[A], ¿cuál es tu placer culposo musical que jamás pondrías en el party?",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
    tipo: "verdad",
  },
  {
    id: "vr-v-004",
    juego: "verdad-reto",
    texto: "[A], ¿cuál fue tu etapa más cringe y cuántos años tenías?",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
    tipo: "verdad",
  },
  {
    id: "vr-v-005",
    juego: "verdad-reto",
    texto: "[A], ¿a qué le tienes miedo que casi nadie sabe?",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
    tipo: "verdad",
  },
  {
    id: "vr-v-006",
    juego: "verdad-reto",
    texto: "[A], di la verdad: ¿qué app abres primero cuando despiertas?",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
    tipo: "verdad",
  },
  {
    id: "vr-v-007",
    juego: "verdad-reto",
    texto: "[A], ¿qué es lo más raro que has hecho cuando estás solo en tu casa?",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
    tipo: "verdad",
  },

  // --- picante ---
  {
    id: "vr-v-008",
    juego: "verdad-reto",
    texto: "[A], ¿qué es lo más arrebatao que has hecho por un ex?",
    tag: "neutral",
    intensidad: "picante",
    fuente: "fabrica",
    tipo: "verdad",
  },
  {
    id: "vr-v-009",
    juego: "verdad-reto",
    texto: "[A], ¿alguna vez te has hecho el dormío pa' no responder un mensaje? ¿a quién?",
    tag: "neutral",
    intensidad: "picante",
    fuente: "fabrica",
    tipo: "verdad",
  },
  {
    id: "vr-v-010",
    juego: "verdad-reto",
    texto: "[A], ¿stalkeaste a alguien hoy? Di la verdad: ¿a quién?",
    tag: "neutral",
    intensidad: "picante",
    fuente: "fabrica",
    tipo: "verdad",
  },
  {
    id: "vr-v-011",
    juego: "verdad-reto",
    texto: "[A], ¿cuál ha sido tu jangueo más arrepentío?",
    tag: "neutral",
    intensidad: "picante",
    fuente: "fabrica",
    tipo: "verdad",
  },
  {
    id: "vr-v-012",
    juego: "verdad-reto",
    texto: "[A], ¿cuántos chats tienes en silencio ahora mismo y por qué?",
    tag: "neutral",
    intensidad: "picante",
    fuente: "fabrica",
    tipo: "verdad",
  },
  {
    id: "vr-v-013",
    juego: "verdad-reto",
    texto: "[A], si tuvieras que salir con alguien que [B] elija a ciegas, ¿confías?",
    tag: "interactivo",
    intensidad: "picante",
    fuente: "fabrica",
    tipo: "verdad",
  },

  // --- sin filtro ---
  {
    id: "vr-v-014",
    juego: "verdad-reto",
    texto: "[A], de los que están aquí, ¿a quién le darías un chance y a quién no?",
    tag: "picante",
    intensidad: "sin-filtro",
    fuente: "fabrica",
    tipo: "verdad",
  },
  {
    id: "vr-v-015",
    juego: "verdad-reto",
    texto: "[A], di la verdad: ¿hay alguien de este coro que te gusta?",
    tag: "picante",
    intensidad: "sin-filtro",
    fuente: "fabrica",
    tipo: "verdad",
  },
  {
    id: "vr-v-016",
    juego: "verdad-reto",
    texto: "[A], ¿cuál es el secreto que jurabas que ibas a llevarte a la tumba?",
    tag: "neutral",
    intensidad: "sin-filtro",
    fuente: "fabrica",
    tipo: "verdad",
  },
  {
    id: "vr-v-017",
    juego: "verdad-reto",
    texto: "[A], ranking honesto: ¿quién del coro es el más coqueto y quién el más santo?",
    tag: "picante",
    intensidad: "sin-filtro",
    fuente: "fabrica",
    tipo: "verdad",
  },
  {
    id: "vr-v-018",
    juego: "verdad-reto",
    texto: "[A], ¿qué es lo más loco que has hecho estando bebío?",
    tag: "neutral",
    intensidad: "sin-filtro",
    fuente: "fabrica",
    tipo: "verdad",
  },
  {
    id: "vr-v-019",
    juego: "verdad-reto",
    texto: "[A], ¿le has tirao a alguien estando con otra persona? Sí o no... o con nombre.",
    tag: "neutral",
    intensidad: "sin-filtro",
    fuente: "fabrica",
    tipo: "verdad",
  },

  // ===========================================================================
  // YO NUNCA NUNCA  (sin [A]/[B]; la gente reacciona a la vista de todos)
  // ===========================================================================

  // --- suave ---
  {
    id: "yn-001",
    juego: "yo-nunca",
    texto: "Yo nunca nunca me he quedado dormido en el trabajo.",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "yn-002",
    juego: "yo-nunca",
    texto: "Yo nunca nunca le he mentido a mi mai pa' poder salir.",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "yn-003",
    juego: "yo-nunca",
    texto: "Yo nunca nunca me he caído en público y disimulado como si na'.",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "yn-004",
    juego: "yo-nunca",
    texto: "Yo nunca nunca he llegado tarde y le he echado la culpa al tapón.",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "yn-005",
    juego: "yo-nunca",
    texto: "Yo nunca nunca he fingido que sabía de qué hablaban pa' no quedar mal.",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "yn-006",
    juego: "yo-nunca",
    texto: "Yo nunca nunca me he aprendido un baile de TikTok completo a escondidas.",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "yn-007",
    juego: "yo-nunca",
    texto: "Yo nunca nunca he llorado con una novela o una película.",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "yn-008",
    juego: "yo-nunca",
    texto: "Yo nunca nunca me he comido algo que se cayó al piso.",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },

  // --- picante ---
  {
    id: "yn-009",
    juego: "yo-nunca",
    texto: "Yo nunca nunca le he stalkeado el IG a un ex a las 3am.",
    tag: "neutral",
    intensidad: "picante",
    fuente: "fabrica",
  },
  {
    id: "yn-010",
    juego: "yo-nunca",
    texto: "Yo nunca nunca le he escrito a un ex estando bebío.",
    tag: "neutral",
    intensidad: "picante",
    fuente: "fabrica",
  },
  {
    id: "yn-011",
    juego: "yo-nunca",
    texto: "Yo nunca nunca me he hecho el que no vi un mensaje a propósito.",
    tag: "neutral",
    intensidad: "picante",
    fuente: "fabrica",
  },
  {
    id: "yn-012",
    juego: "yo-nunca",
    texto: "Yo nunca nunca he tenido un crush con alguien que no debía.",
    tag: "neutral",
    intensidad: "picante",
    fuente: "fabrica",
  },
  {
    id: "yn-013",
    juego: "yo-nunca",
    texto: "Yo nunca nunca me he hecho una cuenta falsa pa' stalkear a alguien.",
    tag: "neutral",
    intensidad: "picante",
    fuente: "fabrica",
  },
  {
    id: "yn-014",
    juego: "yo-nunca",
    texto: "Yo nunca nunca he mentido sobre dónde estaba.",
    tag: "neutral",
    intensidad: "picante",
    fuente: "fabrica",
  },
  {
    id: "yn-015",
    juego: "yo-nunca",
    texto: "Yo nunca nunca le di like a una foto vieja por accidente y me dio un infarto.",
    tag: "neutral",
    intensidad: "picante",
    fuente: "fabrica",
  },

  // --- sin filtro ---
  {
    id: "yn-016",
    juego: "yo-nunca",
    texto: "Yo nunca nunca me he janguiao con alguien de este mismo coro.",
    tag: "neutral",
    intensidad: "sin-filtro",
    fuente: "fabrica",
  },
  {
    id: "yn-017",
    juego: "yo-nunca",
    texto: "Yo nunca nunca me he janguiao con dos personas el mismo fin de semana.",
    tag: "neutral",
    intensidad: "sin-filtro",
    fuente: "fabrica",
  },
  {
    id: "yn-018",
    juego: "yo-nunca",
    texto: "Yo nunca nunca le he tirao a un amigo de un amigo.",
    tag: "neutral",
    intensidad: "sin-filtro",
    fuente: "fabrica",
  },
  {
    id: "yn-019",
    juego: "yo-nunca",
    texto: "Yo nunca nunca he tenido algo con alguien y después lo he negado.",
    tag: "neutral",
    intensidad: "sin-filtro",
    fuente: "fabrica",
  },
  {
    id: "yn-020",
    juego: "yo-nunca",
    texto: "Yo nunca nunca he tenido un situationship que no quería admitir.",
    tag: "neutral",
    intensidad: "sin-filtro",
    fuente: "fabrica",
  },
  {
    id: "yn-021",
    juego: "yo-nunca",
    texto: "Yo nunca nunca le he mentío a alguien que está en este coro ahora mismo.",
    tag: "neutral",
    intensidad: "sin-filtro",
    fuente: "fabrica",
  },
  {
    id: "yn-022",
    juego: "yo-nunca",
    texto: "Yo nunca nunca me he arrepentío de un jangueo a la mañana siguiente.",
    tag: "neutral",
    intensidad: "sin-filtro",
    fuente: "fabrica",
  },

  // ===========================================================================
  // ¿QUIÉN SOY?  (personajes a imitar; intensidad suave, son presets)
  // ===========================================================================

  // --- Arquetipos dominicanos (el oro local; no son personas reales) ---
  {
    id: "qs-arq-001",
    juego: "quien-soy",
    texto: "El tíguere del colmadón",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-arq-002",
    juego: "quien-soy",
    texto: "La doña del chisme del barrio",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-arq-003",
    juego: "quien-soy",
    texto: "La tía que pregunta cuándo te vas a casar",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-arq-004",
    juego: "quien-soy",
    texto: "El motoconchista en hora pico",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-arq-005",
    juego: "quien-soy",
    texto: "El pastor predicando con el micrófono pegao",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-arq-006",
    juego: "quien-soy",
    texto: "El político en campaña prometiendo de to'",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-arq-007",
    juego: "quien-soy",
    texto: "El que siempre llega tarde a to'",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-arq-008",
    juego: "quien-soy",
    texto: "La novia celosa revisando el teléfono",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-arq-009",
    juego: "quien-soy",
    texto: "El reggaetonero grabando un freestyle",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-arq-010",
    juego: "quien-soy",
    texto: "La influencer haciendo un GRWM",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-arq-011",
    juego: "quien-soy",
    texto: "El que se cree DJ con el celular en el party",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-arq-012",
    juego: "quien-soy",
    texto: "El profesor más arrecho de la escuela",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },

  // --- Música DR ---
  {
    id: "qs-mus-001",
    juego: "quien-soy",
    texto: "Juan Luis Guerra",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-mus-002",
    juego: "quien-soy",
    texto: "Tokischa",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-mus-003",
    juego: "quien-soy",
    texto: "El Alfa",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-mus-004",
    juego: "quien-soy",
    texto: "Romeo Santos",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-mus-005",
    juego: "quien-soy",
    texto: "Natti Natasha",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-mus-006",
    juego: "quien-soy",
    texto: "Fefita la Grande",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-mus-007",
    juego: "quien-soy",
    texto: "Chimbala",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-mus-008",
    juego: "quien-soy",
    texto: "Yailin la Más Viral",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-mus-009",
    juego: "quien-soy",
    texto: "Wilfrido Vargas",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },

  // --- Música internacional / urbano ---
  {
    id: "qs-int-001",
    juego: "quien-soy",
    texto: "Bad Bunny",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-int-002",
    juego: "quien-soy",
    texto: "Karol G",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-int-003",
    juego: "quien-soy",
    texto: "Shakira",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-int-004",
    juego: "quien-soy",
    texto: "Daddy Yankee",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-int-005",
    juego: "quien-soy",
    texto: "Peso Pluma",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-int-006",
    juego: "quien-soy",
    texto: "Michael Jackson",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },

  // --- Deportistas (orgullo dominicano + globales) ---
  {
    id: "qs-dep-001",
    juego: "quien-soy",
    texto: "David Ortiz (Big Papi)",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-dep-002",
    juego: "quien-soy",
    texto: "Juan Soto",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-dep-003",
    juego: "quien-soy",
    texto: "Lionel Messi",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-dep-004",
    juego: "quien-soy",
    texto: "Cristiano Ronaldo",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },

  // --- Anime / caricaturas / cine ---
  {
    id: "qs-toon-001",
    juego: "quien-soy",
    texto: "Goku",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-toon-002",
    juego: "quien-soy",
    texto: "Spider-Man",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-toon-003",
    juego: "quien-soy",
    texto: "Naruto",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-toon-004",
    juego: "quien-soy",
    texto: "Bob Esponja",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-toon-005",
    juego: "quien-soy",
    texto: "Shrek",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-toon-006",
    juego: "quien-soy",
    texto: "Homero Simpson",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
  {
    id: "qs-toon-007",
    juego: "quien-soy",
    texto: "Batman",
    tag: "neutral",
    intensidad: "suave",
    fuente: "fabrica",
  },
];